--- #YAML:1.0
name:               Voldemort
version:            0.11
abstract:           ~
author:
    - Spencer Portee (exussum@gmail.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Google::ProtocolBuffers:  0.08
    Moose:                0.54
    Test::More:           0.88
    Test::Simple:         0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
